### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by johnboiles** [apadalko/RadialTransition_objC#2]
Great work on this.

Question: how is this code licensed? If you don't feel strongly, most projects on CocoaControls use the MIT license. It's super developer friendly. Modified BSD license is also one I've used in the past.

Info on licensing here: https://help.github.com/articles/open-source-licensing/

**Comment by apadalko** [comment]
Hi, I've added MIT  license , thank you

**Comment by johnboiles** [comment]
Thanks!
